name: Pets
main: LostTeam\Main
version: 0.6.1_BETA
api: [1.13.1, 2.0.0]
description: ""
author: "LostTeam"
commands:
  pets:
    usage: "/pets <SubCommand>"
    description: "Primary Pets Command"
    permission: pets.command
  pet:
    usage: "/pet <SubCommand>"
    description: "Primary Pets Command"
    permission: pets.command
Permissions:
  pets.command:
    default: true
    children:
      pets.command.list:
        default: op
      pets.command.help:
        default: true
      pets.command.cycle:
        default: true
      pets.command.clear:
        default: op
